# Generated by Django 5.1 on 2024-08-15 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id_compagnie', models.IntegerField(primary_key=True, serialize=False)),
                ('name_compagnie', models.CharField(max_length=50)),
                ('email_compagnie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id_conducteur', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id_trajet', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_escale', models.IntegerField()),
                ('id_compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.compagnie')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('matricule_vehicule', models.IntegerField(primary_key=True, serialize=False)),
                ('marque_vehicule', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('type_vehicule', models.CharField(max_length=20)),
                ('default_places', models.IntegerField()),
                ('availables_places', models.IntegerField()),
                ('id_conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.conducteur')),
            ],
        ),
    ]
