# Generated by Django 5.1 on 2024-08-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='id_compagnie',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='id_conducteur',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='id_trajet',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
