# Generated by Django 5.1 on 2024-08-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_client_id_client_alter_compagnie_id_compagnie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False)),
                ('booking_with_escale', models.BooleanField(default=True)),
                ('places_reservees', models.IntegerField()),
                ('booked_vehicles', models.CharField(choices=[('V', 'Voiture'), ('M', 'Moto'), ('T', 'Tricycle'), ('B', 'Bus')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='trajet',
            name='trajet_with_escale',
            field=models.BooleanField(default=True),
        ),
    ]
